app:
  title: "fastapi template"
  description: "A simple template for fastapi and complete workflow"
  version: "0.1.0"
  openapi_url: "/openapi.json"
  prefix: "/api"

db:
  postgres_db: "glsoft-fastapi"
  postgres_host: "localhost"
  postgres_port: 5432
  postgres_user: "postgres"
  postgres_password: "m3ow87"
  postgres_test_port: 5432

pgadmin:
  default_email: "admin@pgadmin.org"
  listen_port: 5050
  default_password: "admin"
  ssl_mode: "disable"

core:
  secret_key: "m3ow87"
  access_token_expire_minutes: 11520
  access_token_algorithm: "HS256"
